### ISSUE TITLE
Problem with bashrc_iCub with SN.47 Prague01

### ISSUE THREAD

**Issue by Uboldi80** [icub-tech-iit/icub-os-files#2] opened 2021-06-04 09:14 UTC
we noticed that in the robot SN.47 the bashrc_iCub file (2 March 2021 official repository) was not exporting correctly the folders path.
In particular after the process of installation of the superbuild, when we were trying to launch applications on iCub head from a folder different from the robot folder (example: iCubhead home directory or yarpmanager) the command didn't work.

after replacing the bashrc iCub file with the same file of an other robot (iCub3) it worked.
attached you can find the file currently working on the iCub head.
We noticed some differences from this file and the original one (March 2021) and are wondering what  causes the problem 
[bashrc icub testa SN.47 funzionante.txt](https://github.com/icub-tech-iit/icub-os-files/files/6597195/bashrc.icub.testa.SN.47.funzionante.txt)
cc @violadelbono  @traversaro

**Comment by pattacini** [comment] 2021-06-04 09:17
cc @mbrunettini

**Comment by mbrunettini** [comment] 2021-06-04 09:23
@Uboldi80 : can you please better explain the following

> when we were trying to launch applications on iCub head from a folder different from the robot folder (example: iCubhead home directory or yarpmanager) the command didn't work.

In details I do not understand the following

> example: iCubhead home directory **or** yarpmanager

The first (_iCubhead home directory_) is a path and the second (_yarpmanager_) is an executable

**Comment by mbrunettini** [comment] 2021-06-04 10:02
While waiting the above explanation from @Uboldi80 (**useful to replicate the problem**), I check differences among the two version of bashrc_icub. The only difference is that in the latest version (the one _supposed_ to be not working) is in the following lines
```
export OBJ_SUBDIR="build"
if [ "$OBJ_SUBDIR" != "" ]; then
...
fi
```

That are not significative (the `if` clause is `true` since var `OBJ_SUBDIR `is defined with the value `build` in the line above)

**Comment by violadelbono** [comment] 2021-06-04 12:31
Ciao @mbrunettini, basically the problem emerged in this way:

After having built and installed the robotology-superbuild, we usually start working with the robot using the yarpmanager gui. So not launching anymore the commands on terminals inside the superbuild folder on icub-head but through the gui. This because the robot has been installed and imported in .local path (someone corrects me if I am wrong).  During this step we faced the issue. Basically when we tried to launch some process that runs on the head (for example `yarprobotinterface`) from the yarpmanager it didn't work because it could not find the correct path from where launching the command. The same happened when we were trying to launch it from a terminal on icub-head in /home/icub for the same reason.

Maybe @davidetome can explain better since he found the solution.

> That are not significative (the `if` clause is `true` since var `OBJ_SUBDIR` is defined with the value `build` in the line above)

I agree, so this issue seems robot-related, also because we used the same bashrc\_iCub file for Zagreb01 and other robots. :thinking:

**Comment by mbrunettini** [comment] 2021-06-04 12:38
as you can see in both files ([the orginal](https://github.com/icub-tech-iit/icub-os-files/blob/master/user-environment/bashrc_iCub_superbuild) and the one you uploaded here) there is no (re)definition of PATH env variable. this because it is done in 
`source ${ROBOTOLOGY_SUPERBUILD_INSTALL_DIR}/share/robotology-superbuild/setup.sh`
which is identical in both files. This drives me to think that the problem is NOT in .bashrc file
but if @davidetome and/or @traversaro have different thoughts, suggestions are heavily appreciated

**Comment by mbrunettini** [comment] 2021-06-04 15:53
@davidelasagna restored the default `.bashrc_iCub` as from https://github.com/icub-tech-iit/icub-os-files/blob/master/user-environment/bashrc_iCub_superbuild on iCUB SN047 and all seems to work normally.
Please note that, on latest release of iCubOS, the actual `.bashrc_iCub` is only a symlink to a file 
- SuperBulid version : `.bashrc_iCub` -> `.bashrc_iCub_superbuild`
- vanilla version: `.bashrc_iCub` -> `.bashrc_iCub_normal`

**Comment by mbrunettini** [comment] 2021-06-04 15:54
closing since the issue seems not related to `.bashrc_iCub`
Free to reopen in case of needs.

**Closed as completed by mbrunettini** 2021-06-04 15:54 UTC

**Comment by davidetome** [comment] 2021-06-04 20:50
thank you, guys! 🚀

**Comment by violadelbono** [comment] 2021-06-07 06:55
Thnaks @mbrunettini, indeed together with @davidelasagna we found out that the symbolic link was pointing at the wrong file (normal instead of superbuild).

**Comment by traversaro** [comment] 2021-06-07 07:13
> Thnaks @mbrunettini, indeed together with @davidelasagna we found out that the symbolic link was pointing at the wrong file (normal instead of superbuild).

As we switched to use the superbuild installation by default, if the default .bashrc links to the normal instead of the superbuild, probably we need to change this in the pre-built image? @mbrunettini @davidelasagna
